### ISSUE TITLE
 typo on line 258 of the proprietary-files.txt file in the android_device_samsung_a52sxq 

### ISSUE THREAD

**Issue by Firmeware** [Simon1511/android_device_samsung_a52sxq#1]
Hello 
I think there's a typo on line 258 of the proprietary-files.txt file in the android_device_samsung_a52sxq directory
**vvendor**/lib/libsec2qc_conversion.so
should be 
**vendor**/lib/libsec2qc_conversion.so

Regards

**Comment by Simon1511** [comment]
Has been addressed [here](https://github.com/Simon1511/android_device_samsung_a52sxq/commit/e0f8536907baf25c0d94d5c69e2c2ae4b5cb3894), thanks for noticing.
