### ISSUE TITLE
Branch names

### ISSUE THREAD

**Issue by bphd** [Simon1511/android_device_samsung_a52sxq#2]
sed 's/fourteen/aosp-14/g;s/fourteen-plus/aosp-14.1-.9/g;s/thirteen/aosp-13/g;s/thirteen-plus/aosp-13.1-.9/g'

**Comment by Simon1511** [comment]
Why?

All of these branches are for PixelExperience. Why would you want to rename dead branches (not updated since ages) for a dead project?

If you're looking for something to base another ROM on, use the lineage-21 branch.

**Comment by bphd** [comment]
> Why?
> 
> All of these branches are for PixelExperience. Why would you want to rename dead branches (not updated since ages) for a dead project?
> 
> If you're looking for something to base another ROM on, use the lineage-21 branch.

I know, but clarity, clarity

**Comment by Simon1511** [comment]
> I know, but clarity, clarity

Renaming the branches to what you suggested is way less easy to understand than the current names.

> Speaking of the [devil](something to base another ROM on), I don't get how to handle/articulate your a52s sources to make work `lunch` `brunch` `breakfast` when trying to build a CROM upon it? Like how to avoid errors like `** Don't have a product spec for: 'lineage_a52sxq'`

What is a "CROM" supposed to be?
Besides that, `lunch`, `brunch` and `breakfast` not working just means you haven't properly adjusted the trees if building a ROM other than LineageOS.

**Comment by RisenID** [comment]
`lunch`, `brunch` and `breakfast` not working just means you haven't properly adjusted the trees if building a ROM other than LineageOS.

Or bro didnt source envsetup fr

**Comment by bphd** [comment]
> > I know, but clarity, clarity
> 
> Renaming the branches to what you suggested is way less easy to understand than the current names.

I'm truly sorry but "thirteen" don't make any kind of sense. It's a number. Even you has adopter later what I suggested with the "lineage-21". You can't say that it's way less easy to understand, otherwise you mean that for your own "lineage-" branches

> What is a "CROM" supposed to be? 

Custom read-only memory

> adjusted the trees

That's the part I'm interested into when saying "handle/articulate your a52s sources". So, how?

**Comment by Simon1511** [comment]
> I'm truly sorry but "thirteen" don't make any kind of sense. It's a number. Even you has adopted later what I suggested with the "lineage-21". You can't say that it's way less easy to understand, otherwise you mean that for your own "lineage-" branches

I am not the one choosing these branch names. "Thirteen", "Fourteen" and such were chosen and required as by PixelExperience's guidelines for official devices. Same thing with LineageOS, branch names are always required to be named "lineage-XX" as per guidelines. Simply making up branch names isn't a thing when aiming for official status (which is what I always do, and you should too).

> Custom read-only memory

In other words: You want to build a custom ROM but don't know which one yet?

> That's the part I'm interested into when saying "handle/articulate your a52s sources". So, how?

Sync your preferred ROM's sources, put my trees into it, start building, see what happens, learn how stuff works.
I can't just "tell you what to do" because everything is always different for every ROM out there.

And before you ask for a guide or any help: there are plenty of great guides out there, my recommended one being [the lineageOS wiki](https://wiki.lineageos.org/devices/a52sxq/build/).

**Comment by bphd** [comment]
Saying 

>  required as by PixelExperience's guidelines for official devices. Same thing with LineageOS, branch names are always required to be named "lineage-XX" as per guidelines.

Is utterly different than saying

> way less easy to understand than the current names


> aiming for official status (which is what I always do, and you should too

I personally don't understand why unofficial maintainers don't try to become official ones. At worst they stop release, and what? Their old version would still be available on official sources and they will be marked as not supported, end of story. Why they flee like pest that status? That would give support from the whole community, and that's important for all the users that aren't gurus

> don't know which one yet?

If I get result from those commands, it means I launched them, and they come from somewhere (seemingly a CROM), so how could it make sense that I don't know which to build while actually trying to build and failing because lacking the "adjusted the trees/handle/articulate your a52s sources" part?

> Sync

I guess it means using `repo` command with idk which flags

> put my trees into it

That's the complicated part, the "adjusted the trees/handle/articulate your a52s sources" part I ask about

> start building, see what happens

Already saw and sent you the error

> learn how stuff works

Well I learnt that it hasn't worked and that I needed some more instructions to get rid of the error

> everything is always different 

Sure, I'll figure out the particular part, I only ask there about the common part, the part where your work is involved, the one that you should know because, well, that's the very reason of existence of that work, the "adjusted the trees/handle/articulate your a52s sources" part

> great guides out there

The one I used it like more than 10 years old and talks about completely obsolete concepts today

**Comment by Simon1511** [comment]
Read:

https://github.com/Simon1511/android_device_samsung_a52sxq/commit/390e01cc30929a2de3d9fc4b803abc53a88a0dc0

`. build/envsetup.sh`

`brunch yourrom_a52sxq-ap2a-userdebug` (or `yourrom_a52sxq-ap2a-userdebug`, or `yourrom_a52sxq-userdebug`)

**Comment by bphd** [comment]
@Simon1511 It's not completed, nothing renamed

I already figured out the name I should put after brunch, even if you don't put it the script makes it for you, but that doesn't change the problematic part: the "adjusted the trees/handle/articulate your a52s sources" part

I already read that commit before coming there while comparing the branches, and nothing particular, you adapted for pixel experience or lineage
